package exportmoneyminder;

import java.io.IOException;
import java.io.BufferedReader;
import java.io.FileReader;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class FinancialReport extends javax.swing.JFrame {

    /**
     * Creates new form MoneyMinder
     */
    public FinancialReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANEL = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        HomeBtn = new javax.swing.JLabel();
        IncomeBtn = new javax.swing.JLabel();
        ExpensesBtn = new javax.swing.JLabel();
        AccountsBtn = new javax.swing.JLabel();
        ReportsBtn = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        BackHome = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        expenseTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        fromDate = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        enter = new javax.swing.JButton();
        toDate = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        expense = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        income = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        netBalance = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        incomeTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PANEL.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 73, 174));

        HomeBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HomeBtn.setForeground(new java.awt.Color(255, 255, 255));
        HomeBtn.setText("HOME");
        HomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtnMouseClicked(evt);
            }
        });

        IncomeBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IncomeBtn.setForeground(new java.awt.Color(255, 255, 255));
        IncomeBtn.setText("INCOME");
        IncomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IncomeBtnMouseClicked(evt);
            }
        });

        ExpensesBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ExpensesBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExpensesBtn.setText("EXPENSES");
        ExpensesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpensesBtnMouseClicked(evt);
            }
        });

        AccountsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AccountsBtn.setForeground(new java.awt.Color(255, 255, 255));
        AccountsBtn.setText("ACCOUNTS");
        AccountsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountsBtnMouseClicked(evt);
            }
        });

        ReportsBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ReportsBtn.setForeground(new java.awt.Color(255, 255, 255));
        ReportsBtn.setText("REPORT");

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yunise Madriñan\\Documents\\NetBeansProjects\\MoneyMinder\\src\\main\\java\\assets\\money minder logo.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeBtn)
                .addGap(18, 18, 18)
                .addComponent(IncomeBtn)
                .addGap(18, 18, 18)
                .addComponent(ExpensesBtn)
                .addGap(18, 18, 18)
                .addComponent(AccountsBtn)
                .addGap(18, 18, 18)
                .addComponent(ReportsBtn)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IncomeBtn)
                            .addComponent(HomeBtn)
                            .addComponent(ExpensesBtn)
                            .addComponent(AccountsBtn)
                            .addComponent(ReportsBtn)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BackHome.setBackground(new java.awt.Color(0, 0, 153));
        BackHome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BackHome.setForeground(new java.awt.Color(255, 255, 255));
        BackHome.setText("BACK");
        BackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackHomeActionPerformed(evt);
            }
        });

        expenseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Category", "Amount"
            }
        )
        {
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        }
    );
    jScrollPane2.setViewportView(expenseTable);

    jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
    jLabel13.setForeground(new java.awt.Color(0, 74, 173));
    jLabel13.setText("FINANCIAL REPORT");

    fromDate.setBackground(new java.awt.Color(255, 255, 255));

    jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel16.setForeground(new java.awt.Color(0, 74, 173));
    jLabel16.setText("FROM:");

    enter.setBackground(new java.awt.Color(0, 0, 153));
    enter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
    enter.setForeground(new java.awt.Color(255, 255, 255));
    enter.setText("ENTER");
    enter.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            enterActionPerformed(evt);
        }
    });

    jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel17.setForeground(new java.awt.Color(0, 74, 173));
    jLabel17.setText("TO");

    jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
    jLabel14.setForeground(new java.awt.Color(0, 74, 173));
    jLabel14.setText("INCOME BREAKDOWN");

    jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
    jLabel15.setForeground(new java.awt.Color(0, 74, 173));
    jLabel15.setText("EXPENSES BREAKDOWN");

    jPanel1.setBackground(new java.awt.Color(235, 211, 58));

    jLabel19.setBackground(new java.awt.Color(0, 74, 173));
    jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
    jLabel19.setForeground(new java.awt.Color(255, 255, 255));
    jLabel19.setText("EXPENSE");

    expense.setEditable(false);
    expense.setBackground(new java.awt.Color(235, 211, 58));
    expense.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    expense.setForeground(new java.awt.Color(255, 255, 255));
    expense.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    expense.setText("P 0.00");
    expense.setBorder(null);
    expense.setCaretColor(new java.awt.Color(235, 211, 58));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(expense, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel19))
            .addContainerGap(15, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addComponent(jLabel19)
            .addGap(18, 18, 18)
            .addComponent(expense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel4.setBackground(new java.awt.Color(0, 74, 173));

    jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
    jLabel18.setForeground(new java.awt.Color(255, 255, 255));
    jLabel18.setText("INCOME ");

    income.setEditable(false);
    income.setBackground(new java.awt.Color(0, 74, 173));
    income.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    income.setForeground(new java.awt.Color(255, 255, 255));
    income.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    income.setText("P 0.00");
    income.setBorder(null);
    income.setCaretColor(new java.awt.Color(0, 74, 173));
    income.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            incomeActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(income, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel18))
            .addContainerGap(15, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addComponent(jLabel18)
            .addGap(18, 18, 18)
            .addComponent(income, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jPanel5.setBackground(new java.awt.Color(0, 74, 173));

    jLabel21.setBackground(new java.awt.Color(0, 74, 173));
    jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
    jLabel21.setForeground(new java.awt.Color(255, 255, 255));
    jLabel21.setText("NET BALANCE");

    netBalance.setEditable(false);
    netBalance.setBackground(new java.awt.Color(0, 74, 173));
    netBalance.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    netBalance.setForeground(new java.awt.Color(255, 255, 255));
    netBalance.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    netBalance.setText("P 0.00");
    netBalance.setBorder(null);
    netBalance.setCaretColor(new java.awt.Color(0, 74, 173));

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(17, 17, 17)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(netBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel21))
            .addContainerGap(16, Short.MAX_VALUE))
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addGap(22, 22, 22)
            .addComponent(jLabel21)
            .addGap(18, 18, 18)
            .addComponent(netBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(26, Short.MAX_VALUE))
    );

    incomeTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
        },
        new String [] {
            "Category", "Amount"
        }
    )
    {
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    }
    );
    jScrollPane3.setViewportView(incomeTable);

    javax.swing.GroupLayout PANELLayout = new javax.swing.GroupLayout(PANEL);
    PANEL.setLayout(PANELLayout);
    PANELLayout.setHorizontalGroup(
        PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(PANELLayout.createSequentialGroup()
            .addGap(61, 61, 61)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(47, 47, 47)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(46, 46, 46)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 64, Short.MAX_VALUE))
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANELLayout.createSequentialGroup()
            .addContainerGap(164, Short.MAX_VALUE)
            .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANELLayout.createSequentialGroup()
                    .addComponent(jLabel14)
                    .addGap(108, 108, 108)
                    .addComponent(jLabel15)
                    .addGap(164, 164, 164))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANELLayout.createSequentialGroup()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(34, 34, 34)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(128, 128, 128))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANELLayout.createSequentialGroup()
                    .addComponent(jLabel16)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel17)
                    .addGap(18, 18, 18)
                    .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(enter)
                    .addGap(173, 173, 173))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANELLayout.createSequentialGroup()
                    .addComponent(jLabel13)
                    .addGap(316, 316, 316))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANELLayout.createSequentialGroup()
                    .addComponent(BackHome)
                    .addGap(21, 21, 21))))
    );
    PANELLayout.setVerticalGroup(
        PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(PANELLayout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(27, 27, 27)
            .addComponent(jLabel13)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel16)
                .addComponent(jLabel17)
                .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(enter))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
            .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(30, 30, 30)
            .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel14)
                .addComponent(jLabel15))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(16, 16, 16)
            .addComponent(BackHome)
            .addGap(15, 15, 15))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void clearTablesAndFields() {
        ((DefaultTableModel) incomeTable.getModel()).setRowCount(0);
        ((DefaultTableModel) expenseTable.getModel()).setRowCount(0);
        income.setText("");
        expense.setText("");
        netBalance.setText("");
    }
    
    
    private double processTransactions(String fileName, Date startDate, Date endDate, TableModel model) {
       double totalAmount = 0.0;
        try (BufferedReader reader = new BufferedReader(new FileReader(fileName))) {
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length >= 3) {
                    String dateText = parts[0].trim();
                    Date transactionDate = new SimpleDateFormat("MM-dd-yyyy").parse(dateText);

                    // Check if the transaction date is within the selected range
                    if ((startDate == null || !transactionDate.before(startDate)) &&
                            (endDate == null || !transactionDate.after(endDate))) {

                        String category = parts[1].trim();
                        double amount = Double.parseDouble(parts[2].trim());

                        // Add the transaction to the table
                        addTransactionToTable(category, amount, model);

                        // Update total amount
                        totalAmount += amount;
                    }
                }
            }
        } catch (IOException | ParseException e) {
            e.printStackTrace();
        }
        return totalAmount;
    }

    private void addTransactionToTable(String category, double amount, TableModel model) {
    for (int row = 0; row < model.getRowCount(); row++) {
        String tableCategory = model.getValueAt(row, 0).toString();
        if (tableCategory.equals(category)) {
            double currentAmount = Double.parseDouble(model.getValueAt(row, 1).toString());
            double updatedAmount = currentAmount + amount;
                 
            model.setValueAt(String.format("%.2f", updatedAmount), row, 1);
            return;
        }
    }
    
    ((DefaultTableModel) model).addRow(new Object[]{category, String.format("%.2f", amount)});
    }    
    private void IncomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IncomeBtnMouseClicked
     IncomeTransactions incomePanel= new IncomeTransactions();
     incomePanel.show();
     
     dispose();
    }//GEN-LAST:event_IncomeBtnMouseClicked

    private void ExpensesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpensesBtnMouseClicked
        ExpensesTransactions expensePanel= new ExpensesTransactions();
        expensePanel.show();
    
        dispose();
    }//GEN-LAST:event_ExpensesBtnMouseClicked

    private void HomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtnMouseClicked
        Home home= new Home();
        home.show();
        
        dispose();
    }//GEN-LAST:event_HomeBtnMouseClicked

    private void BackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackHomeActionPerformed
        Home home= new Home();
        home.show();

        dispose();
    }//GEN-LAST:event_BackHomeActionPerformed

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
    clearTablesAndFields();

    // Retrieve values from date pickers
    Date startDate = (Date) fromDate.getDate();
    Date endDate = (Date) toDate.getDate();
    
     if (startDate == null || endDate == null) {
        JOptionPane.showMessageDialog(this, "Please select both start and end dates.", "Error", JOptionPane.ERROR_MESSAGE);
        return; 
    }

    double totalIncome = processTransactions("income.txt", startDate, endDate, incomeTable.getModel());
    double totalExpense = processTransactions("expenses.txt", startDate, endDate, expenseTable.getModel());
    double totalNetBalance = totalIncome - totalExpense;

    income.setText(String.format("P %.2f",totalIncome));
    expense.setText(String.format("P %.2f", totalExpense));
    netBalance.setText(String.format("P %.2f", totalNetBalance));
    }//GEN-LAST:event_enterActionPerformed

    private void AccountsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountsBtnMouseClicked
    Accounts account= new Accounts();
    account.show();
    
    dispose();
    }//GEN-LAST:event_AccountsBtnMouseClicked

    private void incomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountsBtn;
    private javax.swing.JButton BackHome;
    private javax.swing.JLabel ExpensesBtn;
    private javax.swing.JLabel HomeBtn;
    private javax.swing.JLabel IncomeBtn;
    private javax.swing.JPanel PANEL;
    private javax.swing.JLabel ReportsBtn;
    private javax.swing.JButton enter;
    private javax.swing.JTextField expense;
    private javax.swing.JTable expenseTable;
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JTextField income;
    private javax.swing.JTable incomeTable;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField netBalance;
    private com.toedter.calendar.JDateChooser toDate;
    // End of variables declaration//GEN-END:variables
}
