package exportmoneyminder;

public class IncomeTransactions extends javax.swing.JFrame {

    /**
     * Creates new form MoneyMinder
     */
    public IncomeTransactions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANEL = new javax.swing.JPanel();
        AddIncome = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ViewIncome = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BackHome = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        HomeBtn3 = new javax.swing.JLabel();
        IncomeBtnPnl = new javax.swing.JLabel();
        ExpensesBtnPnl = new javax.swing.JLabel();
        AccountsBtnPnl = new javax.swing.JLabel();
        ReportsBtnPnl = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PANEL.setBackground(new java.awt.Color(255, 255, 255));

        AddIncome.setBackground(new java.awt.Color(0, 73, 174));
        AddIncome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddIncomeMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ADD TRANSACTION");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yunise Madriñan\\Documents\\NetBeansProjects\\MoneyMinder\\src\\main\\java\\assets\\add-icon.png")); // NOI18N

        javax.swing.GroupLayout AddIncomeLayout = new javax.swing.GroupLayout(AddIncome);
        AddIncome.setLayout(AddIncomeLayout);
        AddIncomeLayout.setHorizontalGroup(
            AddIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddIncomeLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(62, 62, 62))
        );
        AddIncomeLayout.setVerticalGroup(
            AddIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddIncomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(59, 59, 59))
        );

        ViewIncome.setBackground(new java.awt.Color(0, 73, 174));
        ViewIncome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewIncomeMouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("VIEW TRANSACTIONS");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yunise Madriñan\\Documents\\NetBeansProjects\\MoneyMinder\\src\\main\\java\\assets\\list-icon.png")); // NOI18N

        javax.swing.GroupLayout ViewIncomeLayout = new javax.swing.GroupLayout(ViewIncome);
        ViewIncome.setLayout(ViewIncomeLayout);
        ViewIncomeLayout.setHorizontalGroup(
            ViewIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewIncomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel11)
                .addGap(34, 34, 34))
        );
        ViewIncomeLayout.setVerticalGroup(
            ViewIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewIncomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ViewIncomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(59, 59, 59))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 74, 173));
        jLabel12.setText("INCOME TRANSACTION");

        BackHome.setBackground(new java.awt.Color(0, 0, 153));
        BackHome.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BackHome.setForeground(new java.awt.Color(255, 255, 255));
        BackHome.setText("BACK");
        BackHome.setBorder(null);
        BackHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackHomeActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 73, 174));

        HomeBtn3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        HomeBtn3.setForeground(new java.awt.Color(255, 255, 255));
        HomeBtn3.setText("HOME");
        HomeBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBtn3MouseClicked(evt);
            }
        });

        IncomeBtnPnl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IncomeBtnPnl.setForeground(new java.awt.Color(255, 255, 255));
        IncomeBtnPnl.setText("INCOME");
        IncomeBtnPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IncomeBtnPnlMouseClicked(evt);
            }
        });

        ExpensesBtnPnl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ExpensesBtnPnl.setForeground(new java.awt.Color(255, 255, 255));
        ExpensesBtnPnl.setText("EXPENSES");
        ExpensesBtnPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExpensesBtnPnlMouseClicked(evt);
            }
        });

        AccountsBtnPnl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        AccountsBtnPnl.setForeground(new java.awt.Color(255, 255, 255));
        AccountsBtnPnl.setText("ACCOUNTS");
        AccountsBtnPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AccountsBtnPnlMouseClicked(evt);
            }
        });

        ReportsBtnPnl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ReportsBtnPnl.setForeground(new java.awt.Color(255, 255, 255));
        ReportsBtnPnl.setText("REPORT");
        ReportsBtnPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportsBtnPnlMouseClicked(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\Yunise Madriñan\\Documents\\NetBeansProjects\\MoneyMinder\\src\\main\\java\\assets\\money minder logo.png")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeBtn3)
                .addGap(18, 18, 18)
                .addComponent(IncomeBtnPnl)
                .addGap(18, 18, 18)
                .addComponent(ExpensesBtnPnl)
                .addGap(18, 18, 18)
                .addComponent(AccountsBtnPnl)
                .addGap(18, 18, 18)
                .addComponent(ReportsBtnPnl)
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IncomeBtnPnl)
                    .addComponent(HomeBtn3)
                    .addComponent(ExpensesBtnPnl)
                    .addComponent(AccountsBtnPnl)
                    .addComponent(ReportsBtnPnl))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addContainerGap())
        );

        javax.swing.GroupLayout PANELLayout = new javax.swing.GroupLayout(PANEL);
        PANEL.setLayout(PANELLayout);
        PANELLayout.setHorizontalGroup(
            PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PANELLayout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(ViewIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PANELLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(BackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PANELLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel12)))
                .addGap(216, 216, 216))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PANELLayout.setVerticalGroup(
            PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PANELLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(jLabel12)
                .addGap(77, 77, 77)
                .addComponent(AddIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(ViewIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(BackHome, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackHomeActionPerformed
        Home home= new Home();
        home.show();
        
        dispose();
    }//GEN-LAST:event_BackHomeActionPerformed

    private void AddIncomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddIncomeMouseClicked
       AddIncome addIncome= new AddIncome();
       addIncome.show();
       
       dispose();
    }//GEN-LAST:event_AddIncomeMouseClicked

    private void ViewIncomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewIncomeMouseClicked
       ViewIncome viewIncome= new ViewIncome();
       viewIncome.show();
       
       dispose();
    }//GEN-LAST:event_ViewIncomeMouseClicked

    private void ReportsBtnPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsBtnPnlMouseClicked
        FinancialReport report= new FinancialReport();
        report.show();

        dispose();
    }//GEN-LAST:event_ReportsBtnPnlMouseClicked

    private void AccountsBtnPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountsBtnPnlMouseClicked
        Accounts account= new Accounts();
        account.show();

        dispose();
    }//GEN-LAST:event_AccountsBtnPnlMouseClicked

    private void ExpensesBtnPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpensesBtnPnlMouseClicked
        ExpensesTransactions expensePanel= new ExpensesTransactions();
        expensePanel.show();

        dispose();
    }//GEN-LAST:event_ExpensesBtnPnlMouseClicked

    private void IncomeBtnPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IncomeBtnPnlMouseClicked
        IncomeTransactions incomePanel= new IncomeTransactions();
        incomePanel.show();

        dispose();
    }//GEN-LAST:event_IncomeBtnPnlMouseClicked

    private void HomeBtn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBtn3MouseClicked
        Home home= new Home();
        home.show();

        dispose();
    }//GEN-LAST:event_HomeBtn3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccountsBtnPnl;
    private javax.swing.JLabel AccountsBtnPnl10;
    private javax.swing.JLabel AccountsBtnPnl11;
    private javax.swing.JPanel AddIncome;
    private javax.swing.JButton BackHome;
    private javax.swing.JLabel ExpensesBtnPnl;
    private javax.swing.JLabel ExpensesBtnPnl10;
    private javax.swing.JLabel ExpensesBtnPnl11;
    private javax.swing.JLabel HomeBtn10;
    private javax.swing.JLabel HomeBtn11;
    private javax.swing.JLabel HomeBtn3;
    private javax.swing.JLabel IncomeBtnPnl;
    private javax.swing.JLabel IncomeBtnPnl10;
    private javax.swing.JLabel IncomeBtnPnl11;
    private javax.swing.JPanel PANEL;
    private javax.swing.JLabel ReportsBtnPnl;
    private javax.swing.JLabel ReportsBtnPnl10;
    private javax.swing.JLabel ReportsBtnPnl11;
    private javax.swing.JPanel ViewIncome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
